submit clearblade helm charts
open-ness/edgeapps pull request #35
Opened 2020-12-08 15:45 UTC by ryanmccluretx

2020-12-09 04:44 UTC, abjyoti reviewed
Please add Copyright headers with License info

2020-12-09 04:44 UTC, abjyoti commented on applications/clearblade-edge/clearbladehelm/Chart.yaml
> +apiVersion: v1
Please add Copyright header with License type

2020-12-09 04:44 UTC, abjyoti commented on applications/clearblade-edge/clearbladehelm/templates/pod-intel.yaml
> +apiVersion: v1
Please add Copyright header with License type

2020-12-09 04:44 UTC, abjyoti commented on applications/clearblade-edge/clearbladehelm/templates/pod-intel.yaml
> +kind: Pod
Please add Copyright header with License type

2020-12-09 04:44 UTC, abjyoti commented on applications/clearblade-edge/clearbladehelm/templates/service.yaml
> +apiVersion: v1
Please add Copyright header with License type

2020-12-09 04:44 UTC, abjyoti commented on applications/clearblade-edge/clearbladehelm/templates/volume-claim-intel.yaml
> +apiVersion: v1
Please add Copyright header with License type

2020-12-09 04:44 UTC, abjyoti commented on applications/clearblade-edge/clearbladehelm/templates/volume-intel.yaml
> +apiVersion: v1
Please add Copyright header with License type

2020-12-09 04:44 UTC, abjyoti commented on applications/clearblade-edge/clearbladehelm/values.yaml
> +replicaCount: 1
Please add Copyright header with License type

2020-12-09 11:18 UTC, abjyoti requested changes
Please provide the README.md with details on Getting started/ User Guide information.

2020-12-10 00:04 UTC, amr-mokhtar commented on applications/clearblade-edge/clearbladehelm/values.yaml
> +  #tag: "latest"
Is the tag needed? Should it be `9.7.0` ?

2020-12-10 00:04 UTC, amr-mokhtar commented on applications/clearblade-edge/clearbladehelm/templates/service.yaml
> +      #name: sql
Is this commented line is still needed?

2020-12-10 00:09 UTC, amr-mokhtar commented
> Please provide the README.md with details on Getting started/ User Guide information.

Consider the users who came across this GitHub repo and would like to get started with the Clearblade Edge platform.

2020-12-15 14:36 UTC, BoguInt commented
According to https://helm.sh/docs/chart_best_practices/conventions/:

> The directory that contains a chart MUST have the same name as the chart

2020-12-17 18:58 UTC, ryanmccluretx commented
Added copyrights and readme, got rid of comments in yaml

2020-12-18 09:10 UTC, abjyoti approved these changes
I am fine with resolutions

2020-12-21 22:19 UTC, amr-mokhtar approved these changes
Thanks Clearblade team for the contribution. Welcome to the OpenNESS project!!

2020-12-21 22:19 UTC, merged