Initial commit for Herta Connect
open-ness/edgeapps pull request #77
Opened 2021-09-10 16:37 UTC by hertasecurity

2021-09-13 04:34 UTC, archie951 requested changes

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/README.md
> +* See ourt website at https://herta.ai
See *our

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/helm/hc-openness/templates/NOTES.txt
> +1. Get the application URL by running these commands:
Please add the license in this as well otherwise Travis will report error.

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/helm/hc-openness/templates/_helpers.tpl
> +{{/*
Please add license header here as well

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/helm/hc-openness/templates/deployment.yaml
> +apiVersion: apps/v1
Missing license header

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/helm/hc-openness/templates/hpa.yaml
> +{{- if .Values.autoscaling.enabled }}
Missing license headers.

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/helm/hc-openness/templates/ingress.yaml
> +{{- if .Values.ingress.enabled -}}
Missing license headers

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/helm/hc-openness/templates/service.yaml
> +apiVersion: v1
Missing license headers.

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/helm/hc-openness/templates/serviceaccount.yaml
> +{{- if .Values.serviceAccount.create -}}
Missing license headers.

2021-09-13 04:34 UTC, archie951 commented on applications/herta-connect/helm/hc-openness/templates/tests/test-connection.yaml
> +apiVersion: v1
Missing license headers.

2021-09-13 14:55 UTC, hertasecurity commented on applications/herta-connect/README.md
> +* See ourt website at https://herta.ai
```suggestion
* See our website at https://herta.ai
```

2021-09-14 13:51 UTC, abjyoti approved these changes
Thanks for resolving the review comments

2021-09-14 13:51 UTC, merged